format = "$directory$character"
right_format = """$nix_shell$git_status$git_branch$cmd_duration"""

# Disable the blank line at the start of the prompt
add_newline = false

[line_break]
disabled = true

[character]
success_symbol = " [ﬦ](#f5c2e7 bold)"
error_symbol = " [ﬦ](#f38ba8)"

[hostname]
disabled = true

[cmd_duration]
min_time = 1
format = "(fg:#1e1e2e bg:#1e1e2e)[](fg:#cba6f7 bg:#1e1e2e)[ $duration](fg:#1e1e2e bg:#cba6f7)[](fg:#cba6f7 bg:none) "
disabled = false
style = "fg:#cba6f7 bg:#1e1e2e"

[directory]
format = "(fg:#1e1e2e bg:#1e1e2e)[](fg:#f5c2e7 bg:#1e1e2e)[ $path](fg:#1e1e2e bg:#f5c2e7)[](fg:#f5c2e7 bg:none) "
style = "fg:#d9d7d6 bg:#1e1e2e"
truncation_length = 3
truncate_to_repo=true

[nix_shell]
format = "(fg:#1e1e2e bg:#1e1e2e)[](fg:#94e2d5 bg:#1e1e2e)[](fg:#1e1e2e bg:#94e2d5)[](fg:#94e2d5 bg:none) "
style = "fg:#94e2d5 bg:#1e1e2e"

[git_branch]
format = "(fg:#1e1e2e bg:#1e1e2e)[](fg:#f5e0dc bg:#1e1e2e)[ $branch](fg:#282c34 bg:#f5e0dc)[](fg:#f5e0dc bg:none) "
style = "fg:#f5e0dc bg:#1e1e2e"

[git_status]
format="(fg:#1e1e2e bg:#1e1e2e)[](fg:#f2cdcd bg:#1e1e2e)[ $all_status](fg:#1e1e2e bg:#f2cdcd)[](fg:#f2cdcd bg:none) "
style = "fg:#f2cdcd bg:#1e1e2e"
conflicted = "="
ahead ="${count}"
behind = "${count}"
diverged = "${ahead_count}${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "${count}"

[package]
disabled=true
