format = "$directory$character"
right_format = """$nix_shell$git_status$git_branch$cmd_duration"""

# Disable the blank line at the start of the prompt
add_newline = false

[line_break]
disabled = true

[character]
success_symbol = " [ﬦ](#f5bde6 bold)"
error_symbol = " [ﬦ](#ed8796)"

[hostname]
disabled = true

[cmd_duration]
min_time = 1
format = "(fg:#24273a bg:#24273a)[](fg:#c6a0f6 bg:#24273a)[ $duration](fg:#24273a bg:#c6a0f6)[](fg:#c6a0f6 bg:none) "
disabled = false
style = "fg:#c6a0f6 bg:#24273a"

[directory]
format = "(fg:#24273a bg:#24273a)[](fg:#f5bde6 bg:#24273a)[ $path](fg:#24273a bg:#f5bde6)[](fg:#f5bde6 bg:none) "
style = "fg:#d9d7d6 bg:#24273a"
truncation_length = 3
truncate_to_repo=true

[nix_shell]
format = "(fg:#24273a bg:#24273a)[](fg:#8bd5ca bg:#24273a)[](fg:#24273a bg:#8bd5ca)[](fg:#8bd5ca bg:none) "
style = "fg:#8bd5ca bg:#24273a"

[git_branch]
format = "(fg:#24273a bg:#24273a)[](fg:#f4dbd6 bg:#24273a)[ $branch](fg:#282c34 bg:#f4dbd6)[](fg:#f4dbd6 bg:none) "
style = "fg:#f4dbd6 bg:#24273a"

[git_status]
format="(fg:#24273a bg:#24273a)[](fg:#f0c6c6 bg:#24273a)[ $all_status](fg:#24273a bg:#f0c6c6)[](fg:#f0c6c6 bg:none) "
style = "fg:#f0c6c6 bg:#24273a"
conflicted = "="
ahead ="${count}"
behind = "${count}"
diverged = "${ahead_count}${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "${count}"

[package]
disabled=true
